### ISSUE TITLE
Add "Identify" 

### ISSUE THREAD

**Issue by dyspop** [devmach/vero#2]
This library is great, made my life a lot easier.

I'm wondering why identify is not mapped? http://developers.getvero.com/?javascript#users-identify

I understand many functions trigger identify on the vero side of things, but tag and reidentify do not. Do you simply suggest sending a garbage initializer event (like edit) to trigger vero's identify?

**Comment by devmach** [comment]
Hi @dyspop ,
I'm glad the library was useful for you. I preferred to match function names with the api endpoint (= https://api.getvero.com/api/v2/users/track) so `vero.users.track()` identifies user. 

As a flow: You can start sending events with a some unique id (eg session id) and as soon as user registered / logged in alias it using `vero.users.reidentify()` function with her unique id (=user name or email) and from there on track event's with users unique id. 

Please let me know if you are having a problem with the flow and please feel free to make a pull request if you think a part of the code needs to be fixed.
